# Generated by Django 6.0.1 on 2026-06-09 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_BRANCHES_ASSIGNED', 'User Branches Assigned'), ('BRANCH_CREATED', 'Branch Created'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('SALE_CREATED', 'Sale Created'), ('SALE_RETURNED', 'Sale Returned'), ('EXPENSE_CREATED', 'Expense Created'), ('SHIFT_OPENED', 'Shift Opened'), ('SHIFT_CLOSED', 'Shift Closed')], max_length=80)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='branches.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
