# Generated by Django 6.0.1 on 2026-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_BRANCHES_ASSIGNED', 'User Branches Assigned'), ('BRANCH_CREATED', 'Branch Created'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('SALE_CREATED', 'Sale Created'), ('SALE_RETURNED', 'Sale Returned'), ('EXPENSE_CREATED', 'Expense Created'), ('SHIFT_OPENED', 'Shift Opened'), ('SHIFT_CLOSED', 'Shift Closed'), ('SUPPLIER_CREATED', 'Supplier Created'), ('PURCHASE_ORDER_CREATED', 'Purchase Order Created'), ('PURCHASE_ORDER_RECEIVED', 'Purchase Order Received')], max_length=80),
        ),
    ]
