# Generated by Django 6.0.1 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salereturn_salereturnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='expected_cash',
        ),
        migrations.AddField(
            model_name='cashshift',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='expected_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
