# Generated by Django 6.0.1 on 2026-06-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_difference_remove_sale_expected_cash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='manager_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='receipt_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='risk_notes',
            field=models.TextField(blank=True),
        ),
    ]
